/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from '../../common';

export declare namespace DataTypes {
  export type PublisherRewardsStruct = {
    percentage: PromiseOrValue<BigNumberish>;
    publisherVault: PromiseOrValue<string>;
  };

  export type PublisherRewardsStructOutput = [BigNumber, string] & {
    percentage: BigNumber;
    publisherVault: string;
  };

  export type ZKProofsStruct = {
    inputs: PromiseOrValue<BigNumberish>[][];
    a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>][];
    b: [
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
    ][];
    c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>][];
  };

  export type ZKProofsStructOutput = [
    BigNumber[][],
    [BigNumber, BigNumber][],
    [[BigNumber, BigNumber], [BigNumber, BigNumber]][],
    [BigNumber, BigNumber][]
  ] & {
    inputs: BigNumber[][];
    a: [BigNumber, BigNumber][];
    b: [[BigNumber, BigNumber], [BigNumber, BigNumber]][];
    c: [BigNumber, BigNumber][];
  };

  export type NewAdStruct = {
    metadataURI: PromiseOrValue<string>;
    budget: PromiseOrValue<BigNumberish>;
    maxImpressionPrice: PromiseOrValue<BigNumberish>;
    minBlock: PromiseOrValue<BigNumberish>;
    maxBlock: PromiseOrValue<BigNumberish>;
    targetGroupIds: PromiseOrValue<BigNumberish>[];
  };

  export type NewAdStructOutput = [string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber[]] & {
    metadataURI: string;
    budget: BigNumber;
    maxImpressionPrice: BigNumber;
    minBlock: BigNumber;
    maxBlock: BigNumber;
    targetGroupIds: BigNumber[];
  };

  export type ZKPRequestStruct = {
    validator: PromiseOrValue<string>;
    query: ICircuitValidator.CircuitQueryStruct;
    metadataURI: PromiseOrValue<string>;
  };

  export type ZKPRequestStructOutput = [string, ICircuitValidator.CircuitQueryStructOutput, string] & {
    validator: string;
    query: ICircuitValidator.CircuitQueryStructOutput;
    metadataURI: string;
  };
}

export declare namespace ICircuitValidator {
  export type CircuitQueryStruct = {
    schema: PromiseOrValue<BigNumberish>;
    slotIndex: PromiseOrValue<BigNumberish>;
    operator: PromiseOrValue<BigNumberish>;
    value: PromiseOrValue<BigNumberish>[];
    circuitId: PromiseOrValue<string>;
  };

  export type CircuitQueryStructOutput = [BigNumber, BigNumber, BigNumber, BigNumber[], string] & {
    schema: BigNumber;
    slotIndex: BigNumber;
    operator: BigNumber;
    value: BigNumber[];
    circuitId: string;
  };
}

export interface TargecyInterface extends utils.Interface {
  functions: {
    '_adId()': FunctionFragment;
    '_targetGroupId()': FunctionFragment;
    '_zkRequestId()': FunctionFragment;
    'ads(uint256)': FunctionFragment;
    'calculatePercentage(uint256,uint256)': FunctionFragment;
    'consumeAd(uint64,(uint256,address),(uint256[][],uint256[2][],uint256[2][2][],uint256[2][]))': FunctionFragment;
    'createAd((string,uint256,uint256,uint256,uint256,uint256[]))': FunctionFragment;
    'createTargetGroup(string,uint256[])': FunctionFragment;
    'customImpressionPrices(address)': FunctionFragment;
    'defaultImpressionPrice()': FunctionFragment;
    'deleteAd(uint256)': FunctionFragment;
    'deleteTargetGroup(uint256)': FunctionFragment;
    'editAd(uint256,(string,uint256,uint256,uint256,uint256,uint256[]))': FunctionFragment;
    'editTargetGroup(uint256,string,uint256[])': FunctionFragment;
    'owner()': FunctionFragment;
    'paused()': FunctionFragment;
    'protocolVault()': FunctionFragment;
    'renounceOwnership()': FunctionFragment;
    'requestQueries(uint256)': FunctionFragment;
    'setDefaultImpressionPrice(uint256)': FunctionFragment;
    'setProtocolVault(address)': FunctionFragment;
    'setZKPRequest((address,(uint256,uint256,uint256,uint256[],string),string))': FunctionFragment;
    'setZKProofsValidator(address)': FunctionFragment;
    'targetGroupIds(uint256)': FunctionFragment;
    'totalImpressions()': FunctionFragment;
    'transferOwnership(address)': FunctionFragment;
    'verifyZKProof(uint256,uint256[],uint256[2],uint256[2][2],uint256[2])': FunctionFragment;
    'whitelistedPublishers(address)': FunctionFragment;
    'zkProofsValidator()': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | '_adId'
      | '_targetGroupId'
      | '_zkRequestId'
      | 'ads'
      | 'calculatePercentage'
      | 'consumeAd'
      | 'createAd'
      | 'createTargetGroup'
      | 'customImpressionPrices'
      | 'defaultImpressionPrice'
      | 'deleteAd'
      | 'deleteTargetGroup'
      | 'editAd'
      | 'editTargetGroup'
      | 'owner'
      | 'paused'
      | 'protocolVault'
      | 'renounceOwnership'
      | 'requestQueries'
      | 'setDefaultImpressionPrice'
      | 'setProtocolVault'
      | 'setZKPRequest'
      | 'setZKProofsValidator'
      | 'targetGroupIds'
      | 'totalImpressions'
      | 'transferOwnership'
      | 'verifyZKProof'
      | 'whitelistedPublishers'
      | 'zkProofsValidator'
  ): FunctionFragment;

  encodeFunctionData(functionFragment: '_adId', values?: undefined): string;
  encodeFunctionData(functionFragment: '_targetGroupId', values?: undefined): string;
  encodeFunctionData(functionFragment: '_zkRequestId', values?: undefined): string;
  encodeFunctionData(functionFragment: 'ads', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(
    functionFragment: 'calculatePercentage',
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: 'consumeAd',
    values: [PromiseOrValue<BigNumberish>, DataTypes.PublisherRewardsStruct, DataTypes.ZKProofsStruct]
  ): string;
  encodeFunctionData(functionFragment: 'createAd', values: [DataTypes.NewAdStruct]): string;
  encodeFunctionData(
    functionFragment: 'createTargetGroup',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(functionFragment: 'customImpressionPrices', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: 'defaultImpressionPrice', values?: undefined): string;
  encodeFunctionData(functionFragment: 'deleteAd', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: 'deleteTargetGroup', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: 'editAd', values: [PromiseOrValue<BigNumberish>, DataTypes.NewAdStruct]): string;
  encodeFunctionData(
    functionFragment: 'editTargetGroup',
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>, PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
  encodeFunctionData(functionFragment: 'protocolVault', values?: undefined): string;
  encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
  encodeFunctionData(functionFragment: 'requestQueries', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: 'setDefaultImpressionPrice', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: 'setProtocolVault', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: 'setZKPRequest', values: [DataTypes.ZKPRequestStruct]): string;
  encodeFunctionData(functionFragment: 'setZKProofsValidator', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: 'targetGroupIds', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: 'totalImpressions', values?: undefined): string;
  encodeFunctionData(functionFragment: 'transferOwnership', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(
    functionFragment: 'verifyZKProof',
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
    ]
  ): string;
  encodeFunctionData(functionFragment: 'whitelistedPublishers', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: 'zkProofsValidator', values?: undefined): string;

  decodeFunctionResult(functionFragment: '_adId', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: '_targetGroupId', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: '_zkRequestId', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'ads', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'calculatePercentage', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'consumeAd', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createAd', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createTargetGroup', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'customImpressionPrices', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'defaultImpressionPrice', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'deleteAd', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'deleteTargetGroup', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'editAd', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'editTargetGroup', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'protocolVault', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'requestQueries', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setDefaultImpressionPrice', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setProtocolVault', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setZKPRequest', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setZKProofsValidator', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'targetGroupIds', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'totalImpressions', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'verifyZKProof', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'whitelistedPublishers', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'zkProofsValidator', data: BytesLike): Result;

  events: {
    'OwnershipTransferred(address,address)': EventFragment;
    'Paused(address)': EventFragment;
    'Unpaused(address)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Paused'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Unpaused'): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<[string, string], OwnershipTransferredEventObject>;

export type OwnershipTransferredEventFilter = TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface Targecy extends BaseContract {
  contractName: 'Targecy';

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TargecyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _adId(overrides?: CallOverrides): Promise<[BigNumber]>;

    _targetGroupId(overrides?: CallOverrides): Promise<[BigNumber]>;

    _zkRequestId(overrides?: CallOverrides): Promise<[BigNumber]>;

    ads(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        advertiser: string;
        metadataURI: string;
        totalBudget: BigNumber;
        remainingBudget: BigNumber;
        maxImpressionPrice: BigNumber;
        minBlock: BigNumber;
        maxBlock: BigNumber;
        impressions: BigNumber;
      }
    >;

    calculatePercentage(
      total: PromiseOrValue<BigNumberish>,
      percentage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    consumeAd(
      adId: PromiseOrValue<BigNumberish>,
      publisher: DataTypes.PublisherRewardsStruct,
      zkProofs: DataTypes.ZKProofsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createAd(
      ad: DataTypes.NewAdStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createTargetGroup(
      metadataURI: PromiseOrValue<string>,
      zkRequestIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    customImpressionPrices(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[BigNumber]>;

    defaultImpressionPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    deleteAd(
      adId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deleteTargetGroup(
      targetGroupId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    editAd(
      adId: PromiseOrValue<BigNumberish>,
      ad: DataTypes.NewAdStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    editTargetGroup(
      targetGroupId: PromiseOrValue<BigNumberish>,
      metadataURI: PromiseOrValue<string>,
      zkRequestIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    protocolVault(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

    requestQueries(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, ICircuitValidator.CircuitQueryStructOutput, string] & {
        validator: string;
        query: ICircuitValidator.CircuitQueryStructOutput;
        metadataURI: string;
      }
    >;

    setDefaultImpressionPrice(
      _defaultImpressionPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setProtocolVault(
      _protocolVault: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setZKPRequest(
      _zkpRequest: DataTypes.ZKPRequestStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setZKProofsValidator(
      _zkProofsValidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    targetGroupIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { metadataURI: string; impressions: BigNumber }>;

    totalImpressions(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    verifyZKProof(
      requestId: PromiseOrValue<BigNumberish>,
      inputs: PromiseOrValue<BigNumberish>[],
      a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      b: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    whitelistedPublishers(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[boolean]>;

    zkProofsValidator(overrides?: CallOverrides): Promise<[string]>;
  };

  _adId(overrides?: CallOverrides): Promise<BigNumber>;

  _targetGroupId(overrides?: CallOverrides): Promise<BigNumber>;

  _zkRequestId(overrides?: CallOverrides): Promise<BigNumber>;

  ads(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      advertiser: string;
      metadataURI: string;
      totalBudget: BigNumber;
      remainingBudget: BigNumber;
      maxImpressionPrice: BigNumber;
      minBlock: BigNumber;
      maxBlock: BigNumber;
      impressions: BigNumber;
    }
  >;

  calculatePercentage(
    total: PromiseOrValue<BigNumberish>,
    percentage: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  consumeAd(
    adId: PromiseOrValue<BigNumberish>,
    publisher: DataTypes.PublisherRewardsStruct,
    zkProofs: DataTypes.ZKProofsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createAd(
    ad: DataTypes.NewAdStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createTargetGroup(
    metadataURI: PromiseOrValue<string>,
    zkRequestIds: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  customImpressionPrices(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

  defaultImpressionPrice(overrides?: CallOverrides): Promise<BigNumber>;

  deleteAd(
    adId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deleteTargetGroup(
    targetGroupId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  editAd(
    adId: PromiseOrValue<BigNumberish>,
    ad: DataTypes.NewAdStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  editTargetGroup(
    targetGroupId: PromiseOrValue<BigNumberish>,
    metadataURI: PromiseOrValue<string>,
    zkRequestIds: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  protocolVault(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

  requestQueries(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, ICircuitValidator.CircuitQueryStructOutput, string] & {
      validator: string;
      query: ICircuitValidator.CircuitQueryStructOutput;
      metadataURI: string;
    }
  >;

  setDefaultImpressionPrice(
    _defaultImpressionPrice: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setProtocolVault(
    _protocolVault: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setZKPRequest(
    _zkpRequest: DataTypes.ZKPRequestStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setZKProofsValidator(
    _zkProofsValidator: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  targetGroupIds(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { metadataURI: string; impressions: BigNumber }>;

  totalImpressions(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  verifyZKProof(
    requestId: PromiseOrValue<BigNumberish>,
    inputs: PromiseOrValue<BigNumberish>[],
    a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    b: [
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
    ],
    c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    overrides?: CallOverrides
  ): Promise<boolean>;

  whitelistedPublishers(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<boolean>;

  zkProofsValidator(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    _adId(overrides?: CallOverrides): Promise<BigNumber>;

    _targetGroupId(overrides?: CallOverrides): Promise<BigNumber>;

    _zkRequestId(overrides?: CallOverrides): Promise<BigNumber>;

    ads(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        advertiser: string;
        metadataURI: string;
        totalBudget: BigNumber;
        remainingBudget: BigNumber;
        maxImpressionPrice: BigNumber;
        minBlock: BigNumber;
        maxBlock: BigNumber;
        impressions: BigNumber;
      }
    >;

    calculatePercentage(
      total: PromiseOrValue<BigNumberish>,
      percentage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    consumeAd(
      adId: PromiseOrValue<BigNumberish>,
      publisher: DataTypes.PublisherRewardsStruct,
      zkProofs: DataTypes.ZKProofsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    createAd(ad: DataTypes.NewAdStruct, overrides?: CallOverrides): Promise<void>;

    createTargetGroup(
      metadataURI: PromiseOrValue<string>,
      zkRequestIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    customImpressionPrices(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    defaultImpressionPrice(overrides?: CallOverrides): Promise<BigNumber>;

    deleteAd(adId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<void>;

    deleteTargetGroup(targetGroupId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<void>;

    editAd(adId: PromiseOrValue<BigNumberish>, ad: DataTypes.NewAdStruct, overrides?: CallOverrides): Promise<void>;

    editTargetGroup(
      targetGroupId: PromiseOrValue<BigNumberish>,
      metadataURI: PromiseOrValue<string>,
      zkRequestIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    protocolVault(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    requestQueries(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, ICircuitValidator.CircuitQueryStructOutput, string] & {
        validator: string;
        query: ICircuitValidator.CircuitQueryStructOutput;
        metadataURI: string;
      }
    >;

    setDefaultImpressionPrice(
      _defaultImpressionPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setProtocolVault(_protocolVault: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>;

    setZKPRequest(_zkpRequest: DataTypes.ZKPRequestStruct, overrides?: CallOverrides): Promise<void>;

    setZKProofsValidator(_zkProofsValidator: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>;

    targetGroupIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { metadataURI: string; impressions: BigNumber }>;

    totalImpressions(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(newOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>;

    verifyZKProof(
      requestId: PromiseOrValue<BigNumberish>,
      inputs: PromiseOrValue<BigNumberish>[],
      a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      b: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      overrides?: CallOverrides
    ): Promise<boolean>;

    whitelistedPublishers(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<boolean>;

    zkProofsValidator(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    'OwnershipTransferred(address,address)'(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    'Paused(address)'(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    'Unpaused(address)'(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    _adId(overrides?: CallOverrides): Promise<BigNumber>;

    _targetGroupId(overrides?: CallOverrides): Promise<BigNumber>;

    _zkRequestId(overrides?: CallOverrides): Promise<BigNumber>;

    ads(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    calculatePercentage(
      total: PromiseOrValue<BigNumberish>,
      percentage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    consumeAd(
      adId: PromiseOrValue<BigNumberish>,
      publisher: DataTypes.PublisherRewardsStruct,
      zkProofs: DataTypes.ZKProofsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createAd(
      ad: DataTypes.NewAdStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createTargetGroup(
      metadataURI: PromiseOrValue<string>,
      zkRequestIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    customImpressionPrices(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    defaultImpressionPrice(overrides?: CallOverrides): Promise<BigNumber>;

    deleteAd(
      adId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deleteTargetGroup(
      targetGroupId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    editAd(
      adId: PromiseOrValue<BigNumberish>,
      ad: DataTypes.NewAdStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    editTargetGroup(
      targetGroupId: PromiseOrValue<BigNumberish>,
      metadataURI: PromiseOrValue<string>,
      zkRequestIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    protocolVault(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<BigNumber>;

    requestQueries(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    setDefaultImpressionPrice(
      _defaultImpressionPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setProtocolVault(
      _protocolVault: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setZKPRequest(
      _zkpRequest: DataTypes.ZKPRequestStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setZKProofsValidator(
      _zkProofsValidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    targetGroupIds(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    totalImpressions(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    verifyZKProof(
      requestId: PromiseOrValue<BigNumberish>,
      inputs: PromiseOrValue<BigNumberish>[],
      a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      b: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    whitelistedPublishers(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    zkProofsValidator(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    _adId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _targetGroupId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _zkRequestId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ads(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    calculatePercentage(
      total: PromiseOrValue<BigNumberish>,
      percentage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    consumeAd(
      adId: PromiseOrValue<BigNumberish>,
      publisher: DataTypes.PublisherRewardsStruct,
      zkProofs: DataTypes.ZKProofsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createAd(
      ad: DataTypes.NewAdStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createTargetGroup(
      metadataURI: PromiseOrValue<string>,
      zkRequestIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    customImpressionPrices(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    defaultImpressionPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deleteAd(
      adId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deleteTargetGroup(
      targetGroupId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    editAd(
      adId: PromiseOrValue<BigNumberish>,
      ad: DataTypes.NewAdStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    editTargetGroup(
      targetGroupId: PromiseOrValue<BigNumberish>,
      metadataURI: PromiseOrValue<string>,
      zkRequestIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolVault(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<PopulatedTransaction>;

    requestQueries(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setDefaultImpressionPrice(
      _defaultImpressionPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setProtocolVault(
      _protocolVault: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setZKPRequest(
      _zkpRequest: DataTypes.ZKPRequestStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setZKProofsValidator(
      _zkProofsValidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    targetGroupIds(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalImpressions(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    verifyZKProof(
      requestId: PromiseOrValue<BigNumberish>,
      inputs: PromiseOrValue<BigNumberish>[],
      a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      b: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    whitelistedPublishers(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    zkProofsValidator(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
