import './helpers/hardhat-imports';
import path from 'path';

import chalk from 'chalk';
import glob from 'glob';
import { removeConsoleLog } from 'hardhat-preprocessor';
import type { HardhatUserConfig } from 'hardhat/config';

import { getMnemonic } from './helpers/functions';

import { hardhatNamedAccounts } from '~common/constants';
import scaffoldConfig from '~common/scaffold.config';
import { hardhatArtifactsDir, hardhatDeploymentsDir, typechainOutDir } from '~helpers/constants/toolkitPaths';

// eslint-disable-next-line no-duplicate-imports
/**
 * ⛳️⛳️⛳️⛳️⛳️⛳️⛳️⛳️⛳️⛳️
 * NOTES:
 * - All the task are located in the tasks folder
 * - network definitions are in getNetworks in the '@scaffold-eth/common/src workspace: `'@scaffold-eth/common/src/functions`
 * - Named hardhat accounts are in the '@scaffold-eth/common/src workspace: `'@scaffold-eth/common/src/constants`
 * - Files generated by hardhat will be outputted to the ./generated folder
 */

/**
 * this loads all the tasks from the tasks folder
 */
if (process.env.BUILDING !== 'true') {
  try {
    glob.sync('./tasks/**/*.ts').forEach((file: string) => {
      require(path.resolve(file) as string);
    });
  } catch (e) {
    console.log(chalk.yellow('--------------------------'));
    console.warn(chalk.red('🙋 Make sure to compile hardhat first: `yarn compile`'));
    console.log(chalk.yellow('...or run hardhat with process.env.BUILDING = true'));
    console.log(chalk.yellow('If you do not compile hardhat, you cannot be able to load the tasks in the tasks folder'));
    console.log(chalk.yellow('--------------------------'));
    console.log(e);
  }
}

/**
 * loads network list and config from '@scaffold-eth/common/src
 */
const networks = {
  // Development
  localhost: {
    url: 'http://127.0.0.1:8545',
    chainId: 1337,

    accounts: {
      mnemonic: getMnemonic(),
      path: "m/44'/60'/0'/0",
      initialIndex: 0,
    },
  },

  // Test
  mumbai: {
    url: 'https://rpc-mumbai.matic.today',
    chainId: 80001,

    accounts: {
      mnemonic: getMnemonic(), // @todo (Martin): have distinct mnemonics for each network
      path: "m/44'/60'/0'/0",
      initialIndex: 0,
    },
  },

  // Production
  matic: {
    url: 'https://polygon-rpc.com/',
    chainId: 137,

    accounts: {
      mnemonic: getMnemonic(), // @todo (Martin): have distinct mnemonics for each network
      path: "m/44'/60'/0'/0",
      initialIndex: 0,
    },
  },
};

/**
 * See {@link hardhatNamedAccounts} to define named accounts
 */
const namedAccounts = hardhatNamedAccounts as {
  [name: string]: string | number | { [network: string]: null | number | string };
};

export const config: HardhatUserConfig = {
  preprocess: {
    eachLine: removeConsoleLog((hre) => hre.network.name !== 'hardhat' && hre.network.name !== 'localhost'),
  },
  defaultNetwork: scaffoldConfig.runtime.targetNetwork,
  namedAccounts: namedAccounts,
  networks: networks,
  solidity: {
    compilers: [
      {
        version: '0.8.10',
        settings: {
          evmVersion: 'byzantium',
          optimizer: {
            enabled: true,
            runs: 250,
          },
          outputSelection: {
            '*': {
              '*': ['storageLayout'],
            },
          },
        },
      },
    ],
  },
  mocha: {
    bail: false,
    allowUncaught: false,
    require: ['ts-node/register'],
    timeout: 300000,
    slow: 9900,
    reporter: process.env.GITHUB_ACTIONS === 'true' ? 'mocha-junit-reporter' : 'spec',
    reporterOptions: {
      mochaFile: 'testresult.xml',
      toConsole: true,
    },
  },
  watcher: {
    compile: {
      tasks: ['compile'],
      files: ['./contracts/**/*'],
      verbose: false,
    },
    test: {
      tasks: [{ command: 'test', params: { testFiles: ['{path}'] } }],
      files: ['./tests/**/*'],
      verbose: true,
      clearOnStart: true,
      start: 'echo Running my test task now..',
    },
  },
  gasReporter: {
    enabled: true,
    coinmarketcap: process.env.COINMARKETCAP_API_KEY,
    currency: 'USD',
  },
  dodoc: {
    runOnCompile: false,
    debugMode: false,
    keepFileStructure: true,
    freshOutput: true,
    outputDir: './generated/docs',
    include: ['contracts'],
  },
  paths: {
    cache: './generated/hardhat/cache',
    artifacts: hardhatArtifactsDir,
    deployments: hardhatDeploymentsDir,
    deploy: './scripts/deploy',
    tests: './tests/hardhat-tests',
  },
  typechain: {
    outDir: typechainOutDir,
    discriminateTypes: true,
  },
  etherscan: {
    apiKey: {
      localhost: 'none',
    },
    customChains: [
      {
        network: 'localhost',
        chainId: 1337,
        urls: {
          apiURL: 'http://localhost:8090/api',
          browserURL: 'http://localhost:8090/',
        },
      },
    ],
  },
};
export default config;
