version: '3.9'

services:
  redis_db:
    extends:
      file: ./services/docker-compose-redis.yml
      service: redis_db
    mem_limit: 100m

  db-init:
    extends:
      file: ./services/docker-compose-db.yml
      service: db-init
    mem_limit: 256m

  db:
    extends:
      file: ./services/docker-compose-db.yml
      service: db
    mem_limit: 512m

  backend:
    depends_on:
      - db
      - redis_db
    extends:
      file: ./services/docker-compose-backend.yml
      service: backend
    mem_limit: 512m
    links:
      - db:database
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'ganache'
        ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8545/
        INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'true'
        INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
        CHAIN_ID: '1337'

  visualizer:
    extends:
      file: ./services/docker-compose-visualizer.yml
      service: visualizer
    mem_limit: 256m

  sig-provider:
    extends:
      file: ./services/docker-compose-sig-provider.yml
      service: sig-provider
    mem_limit: 256m

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/docker-compose-frontend.yml
      service: frontend
    mem_limit: 1024m

  stats-db-init:
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats-db-init
    mem_limit: 256m

  stats-db:
    depends_on:
      - backend
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats-db
    mem_limit: 512m

  stats:
    depends_on:
      - stats-db
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats
    mem_limit: 256m

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/docker-compose-nginx.yml
      service: proxy
    mem_limit: 256m
