#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged -p 2

# Prevent localhost.json from being committed
git update-index --skip-worktree packages/webapp/src/generated/config/localhost.json packages/sdk/src/generated/config/localhost.json packages/relayer/src/generated/config/localhost.json

# @todo : run based on commit changes
yarn build-backend
yarn build-sdk
yarn compile-contracts
yarn build-dapp
yarn build-relayer
