name: Build Workflow

on:
  push:
    paths:
      - 'packages/backend/**'
      - 'packages/webapp/**'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.modified, 'packages/backend/') ||
      contains(github.event.head_commit.added, 'packages/backend/') ||
      contains(github.event.head_commit.removed, 'packages/backend/')
    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Build Backend
        run: yarn build-backend

  build-webapp:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.modified, 'packages/webapp/') ||
      contains(github.event.head_commit.added, 'packages/webapp/') ||
      contains(github.event.head_commit.removed, 'packages/webapp/')
    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Build WebApp
        run: yarn build-dapp
